// lib/caribbeanCountries.ts

export type CaribbeanCountry = {
  code: string
  name: string
  currency: string
  currencySymbol: string
  region:
    | "Greater Antilles"
    | "Lesser Antilles"
    | "Dutch Caribbean"
    | "Lucayan"
  featured: boolean
  mainCity: string
  majorCities: string[]
  monthlyCostIndexSingle: number
  monthlyCostIndexFamily: number
  defaultRentSingle: number
  defaultRentFamily: number
  startupCosts: {
    visa: number
    flight: number
    temporaryHousing: number
    setup: number
    depositMonths: number
  }
  healthcareMonthlySingle: number
  healthcareMonthlyFamily: number
}

// lib/caribbeanCountryCodes.ts

export const CARIBBEAN_COUNTRY_CODES = [
  "AG",    // Antigua and Barbuda
  "AW",    // Aruba
  "BB",    // Barbados
  "BL",    // Saint Barthélemy
  "BQ-BO", // Bonaire
  "BQ-SA", // Saba
  "BQ-SE", // Sint Eustatius
  "BS",    // Bahamas
  "CU",    // Cuba
  "CW",    // Curaçao
  "DM",    // Dominica
  "DO",    // Dominican Republic
  "GD",    // Grenada
  "GP",    // Guadeloupe
  "HT",    // Haiti
  "JM",    // Jamaica
  "KN",    // Saint Kitts and Nevis
  "KY",    // Cayman Islands
  "LC",    // Saint Lucia
  "MF",    // Saint Martin
  "MQ",    // Martinique
  "MS",    // Montserrat
  "PR",    // Puerto Rico
  "SX",    // Sint Maarten
  "TC",    // Turks and Caicos Islands
  "TT",    // Trinidad and Tobago
  "VC",    // Saint Vincent and the Grenadines
  "VG",    // British Virgin Islands
  "VI",    // U.S. Virgin Islands
] as const

export type CaribbeanCountryCode =
  typeof CARIBBEAN_COUNTRY_CODES[number]

export function isCaribbeanCountryCode(
  code?: string
): code is CaribbeanCountryCode {
  return !!code && CARIBBEAN_COUNTRY_CODES.includes(code as CaribbeanCountryCode)
}

export const CARIBBEAN_COUNTRIES: CaribbeanCountry[] = [
  {
    code: "AG",
    name: "Antigua and Barbuda",
    currency: "XCD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: true,
    mainCity: "Saint John's",
    majorCities: ["Saint John's"],
    monthlyCostIndexSingle: 1.08,
    monthlyCostIndexFamily: 1.12,
    defaultRentSingle: 1400,
    defaultRentFamily: 2200,
    startupCosts: {
      visa: 150,
      flight: 550,
      temporaryHousing: 900,
      setup: 1200,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 180,
    healthcareMonthlyFamily: 420,
  },
  {
    code: "AW",
    name: "Aruba",
    currency: "AWG",
    currencySymbol: "ƒ",
    region: "Dutch Caribbean",
    featured: true,
    mainCity: "Oranjestad",
    majorCities: ["Oranjestad", "San Nicolaas", "Noord"],
    monthlyCostIndexSingle: 1.18,
    monthlyCostIndexFamily: 1.22,
    defaultRentSingle: 1650,
    defaultRentFamily: 2600,
    startupCosts: {
      visa: 250,
      flight: 500,
      temporaryHousing: 1100,
      setup: 1400,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 220,
    healthcareMonthlyFamily: 520,
  },
  {
    code: "BS",
    name: "Bahamas",
    currency: "BSD",
    currencySymbol: "$",
    region: "Lucayan",
    featured: true,
    mainCity: "Nassau",
    majorCities: ["Nassau", "Freeport"],
    monthlyCostIndexSingle: 1.2,
    monthlyCostIndexFamily: 1.28,
    defaultRentSingle: 1800,
    defaultRentFamily: 2900,
    startupCosts: {
      visa: 300,
      flight: 450,
      temporaryHousing: 1200,
      setup: 1500,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 240,
    healthcareMonthlyFamily: 560,
  },
  {
    code: "BB",
    name: "Barbados",
    currency: "BBD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: true,
    mainCity: "Bridgetown",
    majorCities: ["Bridgetown", "Speightstown", "Oistins"],
    monthlyCostIndexSingle: 1.12,
    monthlyCostIndexFamily: 1.18,
    defaultRentSingle: 1500,
    defaultRentFamily: 2400,
    startupCosts: {
      visa: 250,
      flight: 500,
      temporaryHousing: 1000,
      setup: 1300,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 220,
    healthcareMonthlyFamily: 500,
  },
  {
    code: "BQ-BO",
    name: "Bonaire",
    currency: "USD",
    currencySymbol: "$",
    region: "Dutch Caribbean",
    featured: false,
    mainCity: "Kralendijk",
    majorCities: ["Kralendijk", "Rincon"],
    monthlyCostIndexSingle: 1.05,
    monthlyCostIndexFamily: 1.1,
    defaultRentSingle: 1350,
    defaultRentFamily: 2150,
    startupCosts: {
      visa: 150,
      flight: 650,
      temporaryHousing: 1000,
      setup: 1200,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 200,
    healthcareMonthlyFamily: 460,
  },
  {
    code: "VG",
    name: "British Virgin Islands",
    currency: "USD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Road Town",
    majorCities: ["Road Town", "Spanish Town"],
    monthlyCostIndexSingle: 1.16,
    monthlyCostIndexFamily: 1.22,
    defaultRentSingle: 1700,
    defaultRentFamily: 2700,
    startupCosts: {
      visa: 250,
      flight: 650,
      temporaryHousing: 1200,
      setup: 1400,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 240,
    healthcareMonthlyFamily: 560,
  },
  {
    code: "KY",
    name: "Cayman Islands",
    currency: "KYD",
    currencySymbol: "$",
    region: "Greater Antilles",
    featured: true,
    mainCity: "George Town",
    majorCities: ["George Town", "West Bay", "Bodden Town"],
    monthlyCostIndexSingle: 1.38,
    monthlyCostIndexFamily: 1.48,
    defaultRentSingle: 2400,
    defaultRentFamily: 3900,
    startupCosts: {
      visa: 350,
      flight: 650,
      temporaryHousing: 1600,
      setup: 1800,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 320,
    healthcareMonthlyFamily: 720,
  },
  {
    code: "CU",
    name: "Cuba",
    currency: "CUP",
    currencySymbol: "$",
    region: "Greater Antilles",
    featured: false,
    mainCity: "Havana",
    majorCities: ["Havana", "Santiago de Cuba", "Camagüey"],
    monthlyCostIndexSingle: 0.62,
    monthlyCostIndexFamily: 0.72,
    defaultRentSingle: 600,
    defaultRentFamily: 950,
    startupCosts: {
      visa: 120,
      flight: 500,
      temporaryHousing: 550,
      setup: 700,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 90,
    healthcareMonthlyFamily: 180,
  },
  {
    code: "CW",
    name: "Curaçao",
    currency: "XCG",
    currencySymbol: "Cg",
    region: "Dutch Caribbean",
    featured: true,
    mainCity: "Willemstad",
    majorCities: ["Willemstad"],
    monthlyCostIndexSingle: 1.08,
    monthlyCostIndexFamily: 1.14,
    defaultRentSingle: 1450,
    defaultRentFamily: 2300,
    startupCosts: {
      visa: 250,
      flight: 550,
      temporaryHousing: 950,
      setup: 1300,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 220,
    healthcareMonthlyFamily: 500,
  },
  {
    code: "DM",
    name: "Dominica",
    currency: "XCD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Roseau",
    majorCities: ["Roseau", "Portsmouth", "Marigot"],
    monthlyCostIndexSingle: 0.9,
    monthlyCostIndexFamily: 0.98,
    defaultRentSingle: 950,
    defaultRentFamily: 1500,
    startupCosts: {
      visa: 150,
      flight: 650,
      temporaryHousing: 700,
      setup: 900,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 140,
    healthcareMonthlyFamily: 320,
  },
  {
    code: "DO",
    name: "Dominican Republic",
    currency: "DOP",
    currencySymbol: "RD$",
    region: "Greater Antilles",
    featured: true,
    mainCity: "Santo Domingo",
    majorCities: ["Santo Domingo", "Santiago de los Caballeros", "Punta Cana"],
    monthlyCostIndexSingle: 0.84,
    monthlyCostIndexFamily: 0.94,
    defaultRentSingle: 950,
    defaultRentFamily: 1600,
    startupCosts: {
      visa: 180,
      flight: 450,
      temporaryHousing: 700,
      setup: 950,
      depositMonths: 2,
    },
    healthcareMonthlySingle: 120,
    healthcareMonthlyFamily: 300,
  },
  {
    code: "GD",
    name: "Grenada",
    currency: "XCD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Saint George's",
    majorCities: ["Saint George's", "Gouyave", "Grenville"],
    monthlyCostIndexSingle: 0.96,
    monthlyCostIndexFamily: 1.03,
    defaultRentSingle: 1100,
    defaultRentFamily: 1750,
    startupCosts: {
      visa: 150,
      flight: 650,
      temporaryHousing: 800,
      setup: 1000,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 150,
    healthcareMonthlyFamily: 340,
  },
  {
    code: "GP",
    name: "Guadeloupe",
    currency: "EUR",
    currencySymbol: "€",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Basse-Terre",
    majorCities: ["Basse-Terre", "Pointe-à-Pitre", "Les Abymes"],
    monthlyCostIndexSingle: 1.1,
    monthlyCostIndexFamily: 1.18,
    defaultRentSingle: 1400,
    defaultRentFamily: 2300,
    startupCosts: {
      visa: 250,
      flight: 700,
      temporaryHousing: 1000,
      setup: 1300,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 220,
    healthcareMonthlyFamily: 500,
  },
  {
    code: "HT",
    name: "Haiti",
    currency: "HTG",
    currencySymbol: "G",
    region: "Greater Antilles",
    featured: false,
    mainCity: "Port-au-Prince",
    majorCities: ["Port-au-Prince", "Cap-Haïtien", "Les Cayes"],
    monthlyCostIndexSingle: 0.68,
    monthlyCostIndexFamily: 0.78,
    defaultRentSingle: 700,
    defaultRentFamily: 1200,
    startupCosts: {
      visa: 120,
      flight: 500,
      temporaryHousing: 650,
      setup: 800,
      depositMonths: 2,
    },
    healthcareMonthlySingle: 110,
    healthcareMonthlyFamily: 240,
  },
  {
    code: "JM",
    name: "Jamaica",
    currency: "JMD",
    currencySymbol: "$",
    region: "Greater Antilles",
    featured: true,
    mainCity: "Kingston",
    majorCities: ["Kingston", "Montego Bay", "Spanish Town"],
    monthlyCostIndexSingle: 0.9,
    monthlyCostIndexFamily: 1,
    defaultRentSingle: 1050,
    defaultRentFamily: 1750,
    startupCosts: {
      visa: 180,
      flight: 450,
      temporaryHousing: 800,
      setup: 1000,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 150,
    healthcareMonthlyFamily: 360,
  },
  {
    code: "MQ",
    name: "Martinique",
    currency: "EUR",
    currencySymbol: "€",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Fort-de-France",
    majorCities: ["Fort-de-France", "Le Lamentin", "Le Robert"],
    monthlyCostIndexSingle: 1.08,
    monthlyCostIndexFamily: 1.16,
    defaultRentSingle: 1350,
    defaultRentFamily: 2200,
    startupCosts: {
      visa: 250,
      flight: 700,
      temporaryHousing: 1000,
      setup: 1250,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 220,
    healthcareMonthlyFamily: 500,
  },
  {
    code: "MS",
    name: "Montserrat",
    currency: "XCD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Brades",
    majorCities: ["Brades", "Little Bay", "Salem"],
    monthlyCostIndexSingle: 0.98,
    monthlyCostIndexFamily: 1.04,
    defaultRentSingle: 1050,
    defaultRentFamily: 1650,
    startupCosts: {
      visa: 150,
      flight: 750,
      temporaryHousing: 850,
      setup: 1000,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 160,
    healthcareMonthlyFamily: 360,
  },
  {
    code: "PR",
    name: "Puerto Rico",
    currency: "USD",
    currencySymbol: "$",
    region: "Greater Antilles",
    featured: true,
    mainCity: "San Juan",
    majorCities: ["San Juan", "Ponce", "Mayagüez"],
    monthlyCostIndexSingle: 0.96,
    monthlyCostIndexFamily: 1.05,
    defaultRentSingle: 1250,
    defaultRentFamily: 2000,
    startupCosts: {
      visa: 0,
      flight: 350,
      temporaryHousing: 850,
      setup: 1000,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 190,
    healthcareMonthlyFamily: 440,
  },
  {
    code: "BQ-SA",
    name: "Saba",
    currency: "USD",
    currencySymbol: "$",
    region: "Dutch Caribbean",
    featured: false,
    mainCity: "The Bottom",
    majorCities: ["The Bottom", "Windwardside"],
    monthlyCostIndexSingle: 1.02,
    monthlyCostIndexFamily: 1.08,
    defaultRentSingle: 1200,
    defaultRentFamily: 1850,
    startupCosts: {
      visa: 150,
      flight: 750,
      temporaryHousing: 900,
      setup: 1100,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 180,
    healthcareMonthlyFamily: 400,
  },
  {
    code: "BL",
    name: "Saint Barthélemy",
    currency: "EUR",
    currencySymbol: "€",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Gustavia",
    majorCities: ["Gustavia", "Saint-Jean"],
    monthlyCostIndexSingle: 1.34,
    monthlyCostIndexFamily: 1.42,
    defaultRentSingle: 2400,
    defaultRentFamily: 3800,
    startupCosts: {
      visa: 250,
      flight: 900,
      temporaryHousing: 1500,
      setup: 1800,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 300,
    healthcareMonthlyFamily: 700,
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    currency: "XCD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Basseterre",
    majorCities: ["Basseterre", "Charlestown"],
    monthlyCostIndexSingle: 1.0,
    monthlyCostIndexFamily: 1.06,
    defaultRentSingle: 1200,
    defaultRentFamily: 1900,
    startupCosts: {
      visa: 180,
      flight: 600,
      temporaryHousing: 850,
      setup: 1050,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 160,
    healthcareMonthlyFamily: 380,
  },
  {
    code: "LC",
    name: "Saint Lucia",
    currency: "XCD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: true,
    mainCity: "Castries",
    majorCities: ["Castries", "Vieux Fort", "Gros Islet"],
    monthlyCostIndexSingle: 0.98,
    monthlyCostIndexFamily: 1.05,
    defaultRentSingle: 1150,
    defaultRentFamily: 1850,
    startupCosts: {
      visa: 180,
      flight: 600,
      temporaryHousing: 850,
      setup: 1000,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 160,
    healthcareMonthlyFamily: 360,
  },
  {
    code: "MF",
    name: "Saint Martin",
    currency: "EUR",
    currencySymbol: "€",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Marigot",
    majorCities: ["Marigot", "Grand Case"],
    monthlyCostIndexSingle: 1.18,
    monthlyCostIndexFamily: 1.26,
    defaultRentSingle: 1800,
    defaultRentFamily: 2900,
    startupCosts: {
      visa: 250,
      flight: 800,
      temporaryHousing: 1300,
      setup: 1600,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 260,
    healthcareMonthlyFamily: 620,
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    currency: "XCD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Kingstown",
    majorCities: ["Kingstown", "Georgetown"],
    monthlyCostIndexSingle: 0.94,
    monthlyCostIndexFamily: 1.0,
    defaultRentSingle: 1050,
    defaultRentFamily: 1650,
    startupCosts: {
      visa: 150,
      flight: 650,
      temporaryHousing: 800,
      setup: 950,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 150,
    healthcareMonthlyFamily: 340,
  },
  {
    code: "BQ-SE",
    name: "Sint Eustatius",
    currency: "USD",
    currencySymbol: "$",
    region: "Dutch Caribbean",
    featured: false,
    mainCity: "Oranjestad",
    majorCities: ["Oranjestad"],
    monthlyCostIndexSingle: 1.0,
    monthlyCostIndexFamily: 1.06,
    defaultRentSingle: 1150,
    defaultRentFamily: 1800,
    startupCosts: {
      visa: 150,
      flight: 750,
      temporaryHousing: 900,
      setup: 1050,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 170,
    healthcareMonthlyFamily: 380,
  },
  {
    code: "SX",
    name: "Sint Maarten",
    currency: "XCG",
    currencySymbol: "Cg",
    region: "Dutch Caribbean",
    featured: true,
    mainCity: "Philipsburg",
    majorCities: ["Philipsburg", "Simpson Bay", "Cole Bay"],
    monthlyCostIndexSingle: 1.16,
    monthlyCostIndexFamily: 1.24,
    defaultRentSingle: 1700,
    defaultRentFamily: 2750,
    startupCosts: {
      visa: 250,
      flight: 650,
      temporaryHousing: 1200,
      setup: 1450,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 240,
    healthcareMonthlyFamily: 560,
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    currency: "TTD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: true,
    mainCity: "Port of Spain",
    majorCities: ["Port of Spain", "San Fernando", "Arima"],
    monthlyCostIndexSingle: 0.92,
    monthlyCostIndexFamily: 1.0,
    defaultRentSingle: 1100,
    defaultRentFamily: 1800,
    startupCosts: {
      visa: 180,
      flight: 550,
      temporaryHousing: 850,
      setup: 1000,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 150,
    healthcareMonthlyFamily: 340,
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    currency: "USD",
    currencySymbol: "$",
    region: "Lucayan",
    featured: true,
    mainCity: "Cockburn Town",
    majorCities: ["Cockburn Town", "Providenciales"],
    monthlyCostIndexSingle: 1.24,
    monthlyCostIndexFamily: 1.34,
    defaultRentSingle: 2100,
    defaultRentFamily: 3400,
    startupCosts: {
      visa: 250,
      flight: 600,
      temporaryHousing: 1400,
      setup: 1600,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 260,
    healthcareMonthlyFamily: 620,
  },
  {
    code: "VI",
    name: "U.S. Virgin Islands",
    currency: "USD",
    currencySymbol: "$",
    region: "Lesser Antilles",
    featured: false,
    mainCity: "Charlotte Amalie",
    majorCities: ["Charlotte Amalie", "Christiansted", "Frederiksted"],
    monthlyCostIndexSingle: 1.1,
    monthlyCostIndexFamily: 1.18,
    defaultRentSingle: 1550,
    defaultRentFamily: 2500,
    startupCosts: {
      visa: 0,
      flight: 500,
      temporaryHousing: 1000,
      setup: 1300,
      depositMonths: 1,
    },
    healthcareMonthlySingle: 220,
    healthcareMonthlyFamily: 500,
  },
]

export const FEATURED_CARIBBEAN_COUNTRIES = CARIBBEAN_COUNTRIES.filter(
  (country) => country.featured
)

export const CARIBBEAN_COUNTRY_OPTIONS = CARIBBEAN_COUNTRIES.map((country) => ({
  value: country.code,
  label: country.name,
}))


export function getCaribbeanCountryByCode(code?: string) {
  return CARIBBEAN_COUNTRIES.find((country) => country.code === code)
}

