export type InternationalCityDefaults = {
  code: string;
  countryCode: string;
  city: string;
  currency: string;
  costIndex: number;

  monthlyDefaults: {
    rent: number;
    groceries: number;
    utilities: number;
    transport: number;
    healthcare: number;
  };

  housing: {
    depositMonths: number;
    lastMonthRentDefault: number;
    furnishedSetupCost: number;
    utilitiesIncludedDefault: "yes" | "no";
  };

  startupCosts: {
    visa: number;
    flight: number;
    shipping: number;
    temporaryStay: number;
    adminFees: number;
    emergencyBuffer: number;
  };

  sources: {
    rent: string;
    groceries: string;
    utilities: string;
    transport: string;
    healthcare: string;
    startup: string;
  };

  updatedAt: string;
};

export const INTERNATIONAL_CITY_DEFAULTS: InternationalCityDefaults[] = [

   {
    code: "PT-LIS",
    countryCode: "PT",
    city: "Lisbon",
    currency: "EUR",
    costIndex: 0.95,
    monthlyDefaults: {
      rent: 2200,
      groceries: 420,
      utilities: 150,
      transport: 45,
      healthcare: 120,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1200,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 250,
      flight: 650,
      shipping: 400,
      temporaryStay: 1800,
      adminFees: 300,
      emergencyBuffer: 5000,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
   {
    code: "PT-OPO",
    countryCode: "PT",
    city: "Porto",
    currency: "EUR",
    costIndex: 0.82,
    monthlyDefaults: {
      rent: 1700,
      groceries: 390,
      utilities: 140,
      transport: 40,
      healthcare: 110,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1100,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 250,
      flight: 650,
      shipping: 400,
      temporaryStay: 1500,
      adminFees: 280,
      emergencyBuffer: 4200,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
   {
    code: "GB-LON",
    countryCode: "GB",
    city: "London",
    currency: "GBP",
    costIndex: 1.22,
    monthlyDefaults: {
      rent: 2800,
      groceries: 520,
      utilities: 210,
      transport: 220,
      healthcare: 90,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1500,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 350,
      flight: 500,
      shipping: 450,
      temporaryStay: 2200,
      adminFees: 300,
      emergencyBuffer: 5500,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
   {
    code: "CA-TOR",
    countryCode: "CA",
    city: "Toronto",
    currency: "CAD",
    costIndex: 1.08,
    monthlyDefaults: {
      rent: 2500,
      groceries: 520,
      utilities: 190,
      transport: 156,
      healthcare: 140,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1400,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 300,
      flight: 350,
      shipping: 450,
      temporaryStay: 2100,
      adminFees: 280,
      emergencyBuffer: 5200,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
    {
    code: "MX-MEX",
    countryCode: "MX",
    city: "Mexico City",
    currency: "MXN",
    costIndex: 0.72,
    monthlyDefaults: {
      rent: 1500,
      groceries: 320,
      utilities: 90,
      transport: 45,
      healthcare: 90,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 900,
      utilitiesIncludedDefault: "no",
    },
    
    startupCosts: {
      visa: 200,
      flight: 300,
      shipping: 350,
      temporaryStay: 1200,
      adminFees: 220,
      emergencyBuffer: 3000,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
    {
    code: "KR-SEL",
    countryCode: "KR",
    city: "Seoul",
    currency: "KRW",
    costIndex: 0.98,
    monthlyDefaults: {
      rent: 2100,
      groceries: 430,
      utilities: 170,
      transport: 75,
      healthcare: 110,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1300,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 250,
      flight: 900,
      shipping: 500,
      temporaryStay: 1800,
      adminFees: 250,
      emergencyBuffer: 4500,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "KR-BUS",
    countryCode: "KR",
    city: "Busan",
    currency: "KRW",
    costIndex: 0.83,
    monthlyDefaults: {
      rent: 1450,
      groceries: 390,
      utilities: 150,
      transport: 65,
      healthcare: 100,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1100,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 250,
      flight: 900,
      shipping: 500,
      temporaryStay: 1400,
      adminFees: 220,
      emergencyBuffer: 3800,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "JP-TYO",
    countryCode: "JP",
    city: "Tokyo",
    currency: "JPY",
    costIndex: 1.18,
    monthlyDefaults: {
      rent: 2600,
      groceries: 520,
      utilities: 190,
      transport: 110,
      healthcare: 140,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1500,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 300,
      flight: 950,
      shipping: 600,
      temporaryStay: 2200,
      adminFees: 320,
      emergencyBuffer: 5200,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "SG-SIN",
    countryCode: "SG",
    city: "Singapore",
    currency: "SGD",
    costIndex: 1.26,
    monthlyDefaults: {
      rent: 3200,
      groceries: 600,
      utilities: 180,
      transport: 120,
      healthcare: 170,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1600,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 350,
      flight: 1100,
      shipping: 650,
      temporaryStay: 2500,
      adminFees: 350,
      emergencyBuffer: 6500,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "TH-BKK",
    countryCode: "TH",
    city: "Bangkok",
    currency: "THB",
    costIndex: 0.68,
    monthlyDefaults: {
      rent: 1100,
      groceries: 280,
      utilities: 100,
      transport: 55,
      healthcare: 85,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 850,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 250,
      flight: 950,
      shipping: 450,
      temporaryStay: 1200,
      adminFees: 220,
      emergencyBuffer: 2800,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "MY-KUL",
    countryCode: "MY",
    city: "Kuala Lumpur",
    currency: "MYR",
    costIndex: 0.62,
    monthlyDefaults: {
      rent: 950,
      groceries: 250,
      utilities: 90,
      transport: 50,
      healthcare: 80,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 800,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 220,
      flight: 900,
      shipping: 420,
      temporaryStay: 1100,
      adminFees: 200,
      emergencyBuffer: 2500,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "AE-DXB",
    countryCode: "AE",
    city: "Dubai",
    currency: "AED",
    costIndex: 1.12,
    monthlyDefaults: {
      rent: 2900,
      groceries: 520,
      utilities: 230,
      transport: 95,
      healthcare: 190,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1700,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 400,
      flight: 850,
      shipping: 600,
      temporaryStay: 2400,
      adminFees: 350,
      emergencyBuffer: 6000,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "AE-AUH",
    countryCode: "AE",
    city: "Abu Dhabi",
    currency: "AED",
    costIndex: 1.02,
    monthlyDefaults: {
      rent: 2500,
      groceries: 500,
      utilities: 210,
      transport: 90,
      healthcare: 180,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1600,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 400,
      flight: 850,
      shipping: 600,
      temporaryStay: 2200,
      adminFees: 320,
      emergencyBuffer: 5400,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "VN-SGN",
    countryCode: "VN",
    city: "Ho Chi Minh City",
    currency: "VND",
    costIndex: 0.57,
    monthlyDefaults: {
      rent: 850,
      groceries: 220,
      utilities: 85,
      transport: 45,
      healthcare: 70,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 700,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 200,
      flight: 950,
      shipping: 380,
      temporaryStay: 950,
      adminFees: 180,
      emergencyBuffer: 2200,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "ID-JKT",
    countryCode: "ID",
    city: "Jakarta",
    currency: "IDR",
    costIndex: 0.55,
    monthlyDefaults: {
      rent: 800,
      groceries: 210,
      utilities: 80,
      transport: 50,
      healthcare: 75,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 720,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 220,
      flight: 1000,
      shipping: 400,
      temporaryStay: 1000,
      adminFees: 180,
      emergencyBuffer: 2300,
    },
    sources: {
     rent: "Housing assumption",
  groceries: "Grocery assumption",
  utilities: "Utilities assumption",
  transport: "Transit assumption",
  healthcare: "Healthcare assumption",
  startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-24",
  },
    {
    code: "US-NYC",
    countryCode: "US",
    city: "New York City",
    currency: "USD",
    costIndex: 1.85,
    monthlyDefaults: {
      rent: 5227,
      groceries: 700,
      utilities: 260,
      transport: 140,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1800,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 2600,
      adminFees: 250,
      emergencyBuffer: 6500,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-LAX",
    countryCode: "US",
    city: "Los Angeles",
    currency: "USD",
    costIndex: 1.45,
    monthlyDefaults: {
      rent: 2800,
      groceries: 620,
      utilities: 220,
      transport: 170,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1600,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 2200,
      adminFees: 250,
      emergencyBuffer: 5200,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-MIA",
    countryCode: "US",
    city: "Miami",
    currency: "USD",
    costIndex: 1.22,
    monthlyDefaults: {
      rent: 2600,
      groceries: 540,
      utilities: 210,
      transport: 125,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1400,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 2100,
      adminFees: 250,
      emergencyBuffer: 4500,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-CHI",
    countryCode: "US",
    city: "Chicago",
    currency: "USD",
    costIndex: 1.05,
    monthlyDefaults: {
      rent: 2200,
      groceries: 500,
      utilities: 210,
      transport: 115,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1300,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1800,
      adminFees: 250,
      emergencyBuffer: 4000,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-ATL",
    countryCode: "US",
    city: "Atlanta",
    currency: "USD",
    costIndex: 0.96,
    monthlyDefaults: {
      rent: 2000,
      groceries: 460,
      utilities: 190,
      transport: 110,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1200,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1600,
      adminFees: 250,
      emergencyBuffer: 3600,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-AUS",
    countryCode: "US",
    city: "Austin",
    currency: "USD",
    costIndex: 1.02,
    monthlyDefaults: {
      rent: 2100,
      groceries: 470,
      utilities: 195,
      transport: 115,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1250,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1650,
      adminFees: 250,
      emergencyBuffer: 3700,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-DAL",
    countryCode: "US",
    city: "Dallas",
    currency: "USD",
    costIndex: 0.93,
    monthlyDefaults: {
      rent: 1900,
      groceries: 455,
      utilities: 190,
      transport: 110,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1200,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1550,
      adminFees: 250,
      emergencyBuffer: 3400,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-SEA",
    countryCode: "US",
    city: "Seattle",
    currency: "USD",
    costIndex: 1.18,
    monthlyDefaults: {
      rent: 2500,
      groceries: 540,
      utilities: 210,
      transport: 120,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1450,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1950,
      adminFees: 250,
      emergencyBuffer: 4300,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-BNA",
    countryCode: "US",
    city: "Nashville",
    currency: "USD",
    costIndex: 0.98,
    monthlyDefaults: {
      rent: 2000,
      groceries: 460,
      utilities: 190,
      transport: 105,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1200,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1600,
      adminFees: 250,
      emergencyBuffer: 3500,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-CLT",
    countryCode: "US",
    city: "Charlotte",
    currency: "USD",
    costIndex: 0.92,
    monthlyDefaults: {
      rent: 1900,
      groceries: 450,
      utilities: 185,
      transport: 105,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1150,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1500,
      adminFees: 250,
      emergencyBuffer: 3300,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
];

export function getCityDefaultsByCode(code: string) {
  return INTERNATIONAL_CITY_DEFAULTS.find((city) => city.code === code) ?? null;
}