export type InternationalCityDefaults = {
  code: string;
  countryCode: string;
  city: string;
  currency: string;
  costIndex: number;

  monthlyDefaults: {
    rent: number;
    groceries: number;
    utilities: number;
    transport: number;
    healthcare: number;
  };

  housing: {
    depositMonths: number;
    lastMonthRentDefault: number;
    furnishedSetupCost: number;
    utilitiesIncludedDefault: "yes" | "no";
  };

  startupCosts: {
    visa: number;
    flight: number;
    shipping: number;
    temporaryStay: number;
    adminFees: number;
    emergencyBuffer: number;
  };

  sources: {
    rent: string;
    groceries: string;
    utilities: string;
    transport: string;
    healthcare: string;
    startup: string;
  };

  updatedAt: string;
};

export const INTERNATIONAL_CITY_DEFAULTS: InternationalCityDefaults[] = [

   {
    code: "PT-LIS",
    countryCode: "PT",
    city: "Lisbon",
    currency: "EUR",
    costIndex: 0.95,
    monthlyDefaults: {
      rent: 2200,
      groceries: 420,
      utilities: 150,
      transport: 45,
      healthcare: 120,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1200,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 250,
      flight: 650,
      shipping: 400,
      temporaryStay: 1800,
      adminFees: 300,
      emergencyBuffer: 5000,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
   {
    code: "PT-OPO",
    countryCode: "PT",
    city: "Porto",
    currency: "EUR",
    costIndex: 0.82,
    monthlyDefaults: {
      rent: 1700,
      groceries: 390,
      utilities: 140,
      transport: 40,
      healthcare: 110,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1100,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 250,
      flight: 650,
      shipping: 400,
      temporaryStay: 1500,
      adminFees: 280,
      emergencyBuffer: 4200,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
   {
    code: "GB-LON",
    countryCode: "GB",
    city: "London",
    currency: "GBP",
    costIndex: 1.22,
    monthlyDefaults: {
      rent: 2800,
      groceries: 520,
      utilities: 210,
      transport: 220,
      healthcare: 90,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1500,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 350,
      flight: 500,
      shipping: 450,
      temporaryStay: 2200,
      adminFees: 300,
      emergencyBuffer: 5500,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
   {
    code: "CA-TOR",
    countryCode: "CA",
    city: "Toronto",
    currency: "CAD",
    costIndex: 1.08,
    monthlyDefaults: {
      rent: 2500,
      groceries: 520,
      utilities: 190,
      transport: 156,
      healthcare: 140,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1400,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 300,
      flight: 350,
      shipping: 450,
      temporaryStay: 2100,
      adminFees: 280,
      emergencyBuffer: 5200,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },

  
  // ---------------------------------------------------------------------------
  // PHILIPPINES
  // ---------------------------------------------------------------------------
  {
    code: "PH-MNL",
    countryCode: "PH",
    city: "Manila",
    currency: "PHP",
    costIndex: 0.68,
    monthlyDefaults: { rent: 1100, groceries: 300, utilities: 110, transport: 55, healthcare: 90 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 900, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 180, flight: 950, shipping: 450, temporaryStay: 1200, adminFees: 220, emergencyBuffer: 2800 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "PH-CEB",
    countryCode: "PH",
    city: "Cebu City",
    currency: "PHP",
    costIndex: 0.55,
    monthlyDefaults: { rent: 800, groceries: 250, utilities: 95, transport: 45, healthcare: 75 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 750, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 180, flight: 980, shipping: 430, temporaryStay: 950, adminFees: 200, emergencyBuffer: 2400 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "PH-DAV",
    countryCode: "PH",
    city: "Davao",
    currency: "PHP",
    costIndex: 0.48,
    monthlyDefaults: { rent: 650, groceries: 220, utilities: 85, transport: 38, healthcare: 65 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 650, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 180, flight: 1000, shipping: 420, temporaryStay: 850, adminFees: 180, emergencyBuffer: 2000 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "PH-BGC",
    countryCode: "PH",
    city: "BGC / Bonifacio Global City",
    currency: "PHP",
    costIndex: 0.78,
    monthlyDefaults: { rent: 1400, groceries: 340, utilities: 125, transport: 60, healthcare: 100 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 1000, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 180, flight: 950, shipping: 450, temporaryStay: 1400, adminFees: 230, emergencyBuffer: 3000 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "PH-ILO",
    countryCode: "PH",
    city: "Iloilo",
    currency: "PHP",
    costIndex: 0.44,
    monthlyDefaults: { rent: 580, groceries: 200, utilities: 80, transport: 35, healthcare: 60 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 600, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 180, flight: 1010, shipping: 410, temporaryStay: 780, adminFees: 170, emergencyBuffer: 1900 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },

  // ---------------------------------------------------------------------------
  // TAIWAN
  // ---------------------------------------------------------------------------
  {
    code: "TW-TPE",
    countryCode: "TW",
    city: "Taipei",
    currency: "TWD",
    costIndex: 0.84,
    monthlyDefaults: { rent: 1600, groceries: 360, utilities: 140, transport: 70, healthcare: 90 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 1100, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 200, flight: 900, shipping: 500, temporaryStay: 1600, adminFees: 240, emergencyBuffer: 3500 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "TW-KHH",
    countryCode: "TW",
    city: "Kaohsiung",
    currency: "TWD",
    costIndex: 0.66,
    monthlyDefaults: { rent: 1100, groceries: 300, utilities: 120, transport: 55, healthcare: 75 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 900, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 200, flight: 920, shipping: 480, temporaryStay: 1200, adminFees: 210, emergencyBuffer: 2900 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "TW-TXG",
    countryCode: "TW",
    city: "Taichung",
    currency: "TWD",
    costIndex: 0.70,
    monthlyDefaults: { rent: 1200, groceries: 310, utilities: 125, transport: 58, healthcare: 78 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 950, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 200, flight: 910, shipping: 485, temporaryStay: 1300, adminFees: 215, emergencyBuffer: 3000 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "TW-TNN",
    countryCode: "TW",
    city: "Tainan",
    currency: "TWD",
    costIndex: 0.60,
    monthlyDefaults: { rent: 950, groceries: 280, utilities: 110, transport: 48, healthcare: 68 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 820, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 200, flight: 925, shipping: 470, temporaryStay: 1100, adminFees: 200, emergencyBuffer: 2700 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "TW-HSZ",
    countryCode: "TW",
    city: "Hsinchu",
    currency: "TWD",
    costIndex: 0.72,
    monthlyDefaults: { rent: 1250, groceries: 320, utilities: 128, transport: 60, healthcare: 80 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 970, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 200, flight: 905, shipping: 490, temporaryStay: 1350, adminFees: 220, emergencyBuffer: 3100 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },

  // ---------------------------------------------------------------------------
  // HONG KONG
  // ---------------------------------------------------------------------------
  {
    code: "HK-CEN",
    countryCode: "HK",
    city: "Hong Kong (Central)",
    currency: "HKD",
    costIndex: 1.26,
    monthlyDefaults: { rent: 3000, groceries: 620, utilities: 180, transport: 120, healthcare: 120 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 1800, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 300, flight: 950, shipping: 600, temporaryStay: 2600, adminFees: 350, emergencyBuffer: 7000 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "HK-KWL",
    countryCode: "HK",
    city: "Hong Kong (Kowloon)",
    currency: "HKD",
    costIndex: 1.08,
    monthlyDefaults: { rent: 2400, groceries: 560, utilities: 165, transport: 110, healthcare: 110 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 1600, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 300, flight: 950, shipping: 580, temporaryStay: 2200, adminFees: 320, emergencyBuffer: 6200 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "HK-NTL",
    countryCode: "HK",
    city: "Hong Kong (New Territories)",
    currency: "HKD",
    costIndex: 0.90,
    monthlyDefaults: { rent: 1800, groceries: 500, utilities: 150, transport: 100, healthcare: 100 },
    housing: { depositMonths: 2, lastMonthRentDefault: 0, furnishedSetupCost: 1400, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 300, flight: 950, shipping: 560, temporaryStay: 1800, adminFees: 290, emergencyBuffer: 5400 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },

  // ---------------------------------------------------------------------------
  // INDIA
  // ---------------------------------------------------------------------------
  {
    code: "IN-BLR",
    countryCode: "IN",
    city: "Bangalore",
    currency: "INR",
    costIndex: 0.56,
    monthlyDefaults: { rent: 900, groceries: 240, utilities: 90, transport: 50, healthcare: 70 },
    housing: { depositMonths: 3, lastMonthRentDefault: 0, furnishedSetupCost: 800, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 160, flight: 1000, shipping: 480, temporaryStay: 1000, adminFees: 200, emergencyBuffer: 2600 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "IN-DEL",
    countryCode: "IN",
    city: "Delhi / New Delhi",
    currency: "INR",
    costIndex: 0.52,
    monthlyDefaults: { rent: 800, groceries: 210, utilities: 85, transport: 45, healthcare: 65 },
    housing: { depositMonths: 3, lastMonthRentDefault: 0, furnishedSetupCost: 740, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 160, flight: 1000, shipping: 470, temporaryStay: 950, adminFees: 190, emergencyBuffer: 2400 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "IN-MUM",
    countryCode: "IN",
    city: "Mumbai",
    currency: "INR",
    costIndex: 0.62,
    monthlyDefaults: { rent: 1100, groceries: 260, utilities: 95, transport: 55, healthcare: 75 },
    housing: { depositMonths: 3, lastMonthRentDefault: 0, furnishedSetupCost: 860, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 160, flight: 1000, shipping: 490, temporaryStay: 1100, adminFees: 210, emergencyBuffer: 2800 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "IN-HYD",
    countryCode: "IN",
    city: "Hyderabad",
    currency: "INR",
    costIndex: 0.50,
    monthlyDefaults: { rent: 750, groceries: 220, utilities: 80, transport: 42, healthcare: 62 },
    housing: { depositMonths: 3, lastMonthRentDefault: 0, furnishedSetupCost: 720, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 160, flight: 1010, shipping: 460, temporaryStay: 900, adminFees: 185, emergencyBuffer: 2300 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "IN-CHE",
    countryCode: "IN",
    city: "Chennai",
    currency: "INR",
    costIndex: 0.48,
    monthlyDefaults: { rent: 700, groceries: 210, utilities: 78, transport: 40, healthcare: 60 },
    housing: { depositMonths: 3, lastMonthRentDefault: 0, furnishedSetupCost: 700, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 160, flight: 1010, shipping: 455, temporaryStay: 880, adminFees: 180, emergencyBuffer: 2200 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },

  // ---------------------------------------------------------------------------
  // CHINA
  // ---------------------------------------------------------------------------
  {
    code: "CN-SHA",
    countryCode: "CN",
    city: "Shanghai",
    currency: "CNY",
    costIndex: 0.88,
    monthlyDefaults: { rent: 1900, groceries: 420, utilities: 150, transport: 80, healthcare: 110 },
    housing: { depositMonths: 3, lastMonthRentDefault: 0, furnishedSetupCost: 1300, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 250, flight: 1000, shipping: 600, temporaryStay: 1900, adminFees: 310, emergencyBuffer: 4500 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "CN-BJS",
    countryCode: "CN",
    city: "Beijing",
    currency: "CNY",
    costIndex: 0.92,
    monthlyDefaults: { rent: 2000, groceries: 440, utilities: 160, transport: 85, healthcare: 115 },
    housing: { depositMonths: 3, lastMonthRentDefault: 0, furnishedSetupCost: 1350, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 250, flight: 1000, shipping: 610, temporaryStay: 2000, adminFees: 320, emergencyBuffer: 4700 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "CN-SZX",
    countryCode: "CN",
    city: "Shenzhen",
    currency: "CNY",
    costIndex: 0.85,
    monthlyDefaults: { rent: 1750, groceries: 400, utilities: 145, transport: 75, healthcare: 105 },
    housing: { depositMonths: 3, lastMonthRentDefault: 0, furnishedSetupCost: 1250, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 250, flight: 1010, shipping: 595, temporaryStay: 1800, adminFees: 300, emergencyBuffer: 4300 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "CN-GZH",
    countryCode: "CN",
    city: "Guangzhou",
    currency: "CNY",
    costIndex: 0.80,
    monthlyDefaults: { rent: 1550, groceries: 380, utilities: 138, transport: 70, healthcare: 100 },
    housing: { depositMonths: 3, lastMonthRentDefault: 0, furnishedSetupCost: 1180, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 250, flight: 1010, shipping: 585, temporaryStay: 1700, adminFees: 290, emergencyBuffer: 4100 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "CN-CDU",
    countryCode: "CN",
    city: "Chengdu",
    currency: "CNY",
    costIndex: 0.68,
    monthlyDefaults: { rent: 1200, groceries: 330, utilities: 120, transport: 58, healthcare: 88 },
    housing: { depositMonths: 3, lastMonthRentDefault: 0, furnishedSetupCost: 1050, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 250, flight: 1020, shipping: 570, temporaryStay: 1450, adminFees: 270, emergencyBuffer: 3700 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },

  // ---------------------------------------------------------------------------
  // QATAR
  // ---------------------------------------------------------------------------
  {
    code: "QA-DOH",
    countryCode: "QA",
    city: "Doha",
    currency: "QAR",
    costIndex: 1.02,
    monthlyDefaults: { rent: 2300, groceries: 520, utilities: 180, transport: 95, healthcare: 140 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 1600, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 380, flight: 900, shipping: 620, temporaryStay: 2200, adminFees: 330, emergencyBuffer: 5800 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "QA-LUS",
    countryCode: "QA",
    city: "Lusail",
    currency: "QAR",
    costIndex: 1.08,
    monthlyDefaults: { rent: 2500, groceries: 540, utilities: 190, transport: 100, healthcare: 145 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 1700, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 380, flight: 900, shipping: 625, temporaryStay: 2300, adminFees: 340, emergencyBuffer: 6000 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "QA-WAK",
    countryCode: "QA",
    city: "Al Wakrah",
    currency: "QAR",
    costIndex: 0.82,
    monthlyDefaults: { rent: 1700, groceries: 450, utilities: 155, transport: 80, healthcare: 120 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 1300, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 380, flight: 900, shipping: 600, temporaryStay: 1800, adminFees: 300, emergencyBuffer: 4800 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },

  // ---------------------------------------------------------------------------
  // SAUDI ARABIA
  // ---------------------------------------------------------------------------
  {
    code: "SA-RUH",
    countryCode: "SA",
    city: "Riyadh",
    currency: "SAR",
    costIndex: 0.84,
    monthlyDefaults: { rent: 1600, groceries: 360, utilities: 140, transport: 85, healthcare: 130 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 1200, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 350, flight: 880, shipping: 580, temporaryStay: 1800, adminFees: 310, emergencyBuffer: 4500 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "SA-JED",
    countryCode: "SA",
    city: "Jeddah",
    currency: "SAR",
    costIndex: 0.80,
    monthlyDefaults: { rent: 1450, groceries: 340, utilities: 130, transport: 80, healthcare: 120 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 1150, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 350, flight: 900, shipping: 570, temporaryStay: 1700, adminFees: 295, emergencyBuffer: 4200 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "SA-DMM",
    countryCode: "SA",
    city: "Dammam / Eastern Province",
    currency: "SAR",
    costIndex: 0.76,
    monthlyDefaults: { rent: 1300, groceries: 320, utilities: 125, transport: 75, healthcare: 115 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 1080, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 350, flight: 900, shipping: 560, temporaryStay: 1600, adminFees: 280, emergencyBuffer: 4000 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "SA-ABH",
    countryCode: "SA",
    city: "Abha",
    currency: "SAR",
    costIndex: 0.58,
    monthlyDefaults: { rent: 900, groceries: 260, utilities: 100, transport: 60, healthcare: 95 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 880, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 350, flight: 920, shipping: 540, temporaryStay: 1200, adminFees: 250, emergencyBuffer: 3200 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "SA-MED",
    countryCode: "SA",
    city: "Medina",
    currency: "SAR",
    costIndex: 0.62,
    monthlyDefaults: { rent: 1000, groceries: 275, utilities: 108, transport: 64, healthcare: 100 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 920, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 350, flight: 910, shipping: 545, temporaryStay: 1300, adminFees: 258, emergencyBuffer: 3400 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },

  // ---------------------------------------------------------------------------
  // OMAN
  // ---------------------------------------------------------------------------
  {
    code: "OM-MCT",
    countryCode: "OM",
    city: "Muscat",
    currency: "OMR",
    costIndex: 0.80,
    monthlyDefaults: { rent: 1500, groceries: 340, utilities: 130, transport: 75, healthcare: 120 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 1150, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 300, flight: 870, shipping: 560, temporaryStay: 1700, adminFees: 290, emergencyBuffer: 4200 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "OM-SLL",
    countryCode: "OM",
    city: "Salalah",
    currency: "OMR",
    costIndex: 0.62,
    monthlyDefaults: { rent: 1050, groceries: 270, utilities: 105, transport: 58, healthcare: 95 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 900, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 300, flight: 900, shipping: 540, temporaryStay: 1300, adminFees: 255, emergencyBuffer: 3400 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },
  {
    code: "OM-SOH",
    countryCode: "OM",
    city: "Sohar",
    currency: "OMR",
    costIndex: 0.55,
    monthlyDefaults: { rent: 880, groceries: 240, utilities: 95, transport: 50, healthcare: 85 },
    housing: { depositMonths: 1, lastMonthRentDefault: 0, furnishedSetupCost: 820, utilitiesIncludedDefault: "no" },
    startupCosts: { visa: 300, flight: 890, shipping: 530, temporaryStay: 1150, adminFees: 240, emergencyBuffer: 3000 },
    sources: { rent: "City default estimate", groceries: "City default estimate", utilities: "City default estimate", transport: "City default estimate", healthcare: "City default estimate", startup: "City default estimate" },
    updatedAt: "2026-04-09",
  },

  
    {
    code: "MX-MEX",
    countryCode: "MX",
    city: "Mexico City",
    currency: "MXN",
    costIndex: 0.72,
    monthlyDefaults: {
      rent: 1500,
      groceries: 320,
      utilities: 90,
      transport: 45,
      healthcare: 90,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 900,
      utilitiesIncludedDefault: "no",
    },
    
    startupCosts: {
      visa: 200,
      flight: 300,
      shipping: 350,
      temporaryStay: 1200,
      adminFees: 220,
      emergencyBuffer: 3000,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
    {
    code: "KR-SEL",
    countryCode: "KR",
    city: "Seoul",
    currency: "KRW",
    costIndex: 0.98,
    monthlyDefaults: {
      rent: 2100,
      groceries: 430,
      utilities: 170,
      transport: 75,
      healthcare: 110,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1300,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 250,
      flight: 900,
      shipping: 500,
      temporaryStay: 1800,
      adminFees: 250,
      emergencyBuffer: 4500,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "KR-BUS",
    countryCode: "KR",
    city: "Busan",
    currency: "KRW",
    costIndex: 0.83,
    monthlyDefaults: {
      rent: 1450,
      groceries: 390,
      utilities: 150,
      transport: 65,
      healthcare: 100,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1100,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 250,
      flight: 900,
      shipping: 500,
      temporaryStay: 1400,
      adminFees: 220,
      emergencyBuffer: 3800,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "JP-TYO",
    countryCode: "JP",
    city: "Tokyo",
    currency: "JPY",
    costIndex: 1.18,
    monthlyDefaults: {
      rent: 2600,
      groceries: 520,
      utilities: 190,
      transport: 110,
      healthcare: 140,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1500,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 300,
      flight: 950,
      shipping: 600,
      temporaryStay: 2200,
      adminFees: 320,
      emergencyBuffer: 5200,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "SG-SIN",
    countryCode: "SG",
    city: "Singapore",
    currency: "SGD",
    costIndex: 1.26,
    monthlyDefaults: {
      rent: 3200,
      groceries: 600,
      utilities: 180,
      transport: 120,
      healthcare: 170,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1600,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 350,
      flight: 1100,
      shipping: 650,
      temporaryStay: 2500,
      adminFees: 350,
      emergencyBuffer: 6500,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "TH-BKK",
    countryCode: "TH",
    city: "Bangkok",
    currency: "THB",
    costIndex: 0.68,
    monthlyDefaults: {
      rent: 1100,
      groceries: 280,
      utilities: 100,
      transport: 55,
      healthcare: 85,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 850,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 250,
      flight: 950,
      shipping: 450,
      temporaryStay: 1200,
      adminFees: 220,
      emergencyBuffer: 2800,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "MY-KUL",
    countryCode: "MY",
    city: "Kuala Lumpur",
    currency: "MYR",
    costIndex: 0.62,
    monthlyDefaults: {
      rent: 950,
      groceries: 250,
      utilities: 90,
      transport: 50,
      healthcare: 80,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 800,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 220,
      flight: 900,
      shipping: 420,
      temporaryStay: 1100,
      adminFees: 200,
      emergencyBuffer: 2500,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "AE-DXB",
    countryCode: "AE",
    city: "Dubai",
    currency: "AED",
    costIndex: 1.12,
    monthlyDefaults: {
      rent: 2900,
      groceries: 520,
      utilities: 230,
      transport: 95,
      healthcare: 190,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1700,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 400,
      flight: 850,
      shipping: 600,
      temporaryStay: 2400,
      adminFees: 350,
      emergencyBuffer: 6000,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "AE-AUH",
    countryCode: "AE",
    city: "Abu Dhabi",
    currency: "AED",
    costIndex: 1.02,
    monthlyDefaults: {
      rent: 2500,
      groceries: 500,
      utilities: 210,
      transport: 90,
      healthcare: 180,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1600,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 400,
      flight: 850,
      shipping: 600,
      temporaryStay: 2200,
      adminFees: 320,
      emergencyBuffer: 5400,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "VN-SGN",
    countryCode: "VN",
    city: "Ho Chi Minh City",
    currency: "VND",
    costIndex: 0.57,
    monthlyDefaults: {
      rent: 850,
      groceries: 220,
      utilities: 85,
      transport: 45,
      healthcare: 70,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 700,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 200,
      flight: 950,
      shipping: 380,
      temporaryStay: 950,
      adminFees: 180,
      emergencyBuffer: 2200,
    },
    sources: {
      rent: "City default estimate",
      groceries: "City default estimate",
      utilities: "City default estimate",
      transport: "City default estimate",
      healthcare: "City default estimate",
      startup: "City default estimate",
    },
    updatedAt: "2026-03-24",
  },
  {
    code: "ID-JKT",
    countryCode: "ID",
    city: "Jakarta",
    currency: "IDR",
    costIndex: 0.55,
    monthlyDefaults: {
      rent: 800,
      groceries: 210,
      utilities: 80,
      transport: 50,
      healthcare: 75,
    },
    housing: {
      depositMonths: 2,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 720,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 220,
      flight: 1000,
      shipping: 400,
      temporaryStay: 1000,
      adminFees: 180,
      emergencyBuffer: 2300,
    },
    sources: {
     rent: "Housing assumption",
  groceries: "Grocery assumption",
  utilities: "Utilities assumption",
  transport: "Transit assumption",
  healthcare: "Healthcare assumption",
  startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-24",
  },
    {
    code: "US-NYC",
    countryCode: "US",
    city: "New York City",
    currency: "USD",
    costIndex: 1.85,
    monthlyDefaults: {
      rent: 5227,
      groceries: 700,
      utilities: 260,
      transport: 140,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1800,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 2600,
      adminFees: 250,
      emergencyBuffer: 6500,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-LAX",
    countryCode: "US",
    city: "Los Angeles",
    currency: "USD",
    costIndex: 1.45,
    monthlyDefaults: {
      rent: 2800,
      groceries: 620,
      utilities: 220,
      transport: 170,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1600,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 2200,
      adminFees: 250,
      emergencyBuffer: 5200,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-MIA",
    countryCode: "US",
    city: "Miami",
    currency: "USD",
    costIndex: 1.22,
    monthlyDefaults: {
      rent: 2600,
      groceries: 540,
      utilities: 210,
      transport: 125,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1400,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 2100,
      adminFees: 250,
      emergencyBuffer: 4500,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-CHI",
    countryCode: "US",
    city: "Chicago",
    currency: "USD",
    costIndex: 1.05,
    monthlyDefaults: {
      rent: 2200,
      groceries: 500,
      utilities: 210,
      transport: 115,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1300,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1800,
      adminFees: 250,
      emergencyBuffer: 4000,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-ATL",
    countryCode: "US",
    city: "Atlanta",
    currency: "USD",
    costIndex: 0.96,
    monthlyDefaults: {
      rent: 2000,
      groceries: 460,
      utilities: 190,
      transport: 110,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1200,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1600,
      adminFees: 250,
      emergencyBuffer: 3600,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-AUS",
    countryCode: "US",
    city: "Austin",
    currency: "USD",
    costIndex: 1.02,
    monthlyDefaults: {
      rent: 2100,
      groceries: 470,
      utilities: 195,
      transport: 115,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1250,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1650,
      adminFees: 250,
      emergencyBuffer: 3700,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-DAL",
    countryCode: "US",
    city: "Dallas",
    currency: "USD",
    costIndex: 0.93,
    monthlyDefaults: {
      rent: 1900,
      groceries: 455,
      utilities: 190,
      transport: 110,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1200,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1550,
      adminFees: 250,
      emergencyBuffer: 3400,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-SEA",
    countryCode: "US",
    city: "Seattle",
    currency: "USD",
    costIndex: 1.18,
    monthlyDefaults: {
      rent: 2500,
      groceries: 540,
      utilities: 210,
      transport: 120,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1450,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1950,
      adminFees: 250,
      emergencyBuffer: 4300,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-BNA",
    countryCode: "US",
    city: "Nashville",
    currency: "USD",
    costIndex: 0.98,
    monthlyDefaults: {
      rent: 2000,
      groceries: 460,
      utilities: 190,
      transport: 105,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1200,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1600,
      adminFees: 250,
      emergencyBuffer: 3500,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
  {
    code: "US-CLT",
    countryCode: "US",
    city: "Charlotte",
    currency: "USD",
    costIndex: 0.92,
    monthlyDefaults: {
      rent: 1900,
      groceries: 450,
      utilities: 185,
      transport: 105,
      healthcare: 120,
    },
    housing: {
      depositMonths: 1,
      lastMonthRentDefault: 0,
      furnishedSetupCost: 1150,
      utilitiesIncludedDefault: "no",
    },
    startupCosts: {
      visa: 235,
      flight: 700,
      shipping: 500,
      temporaryStay: 1500,
      adminFees: 250,
      emergencyBuffer: 3300,
    },
    sources: {
      rent: "Housing assumption",
      groceries: "Grocery assumption",
      utilities: "Utilities assumption",
      transport: "Transit assumption",
      healthcare: "Healthcare assumption",
      startup: "Relocation setup assumption",
    },
    updatedAt: "2026-03-25",
  },
];

export function getCityDefaultsByCode(code: string) {
  return INTERNATIONAL_CITY_DEFAULTS.find((city) => city.code === code) ?? null;
}